version: "3.4"

x-template: &flyway-template
  image: flyway/flyway:7.0.1
  volumes:
    - ../src/main/resources/db/migration:/flyway/sql
    - ../src/main/resources/conf:/flyway/conf
  depends_on:
    - db

services:
  flyway-clean:
    <<: *flyway-template
    command: clean

  flyway-migrate:
    <<: *flyway-template
    command: migrate

  flyway-info:
    <<: *flyway-template
    command: info

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_TYPE=postgres
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    ports:
      - 5432:5432
    volumes:
      - ../src/main/resources/db/init:/docker-entrypoint-initdb.d
    container_name: db